### ISSUE TITLE
How to limit results?

### ISSUE THREAD

**Issue by holidaycottages** [aichbauer/express-graphql-boilerplate#15]
I have made my own query for my own DB table and want to limit the results, but I cant work out how to pass in a variable that lets me then forward that to the sequlize ?

I can hard code it:

`resolve: (property, args) => Property.findAll({ where: args, limit: 12 })`

But I want to pass that and and offset in

**Comment by aichbauer** [comment]
If I understand the problem correctly you can achieve this by passing additional arguments.

I use the note query to give an example...

```js
const noteQuery = {
  type: new GraphQLList(NoteType),
  args: {
    id: {
      name: 'id',
      type: GraphQLInt,
    },
    limit: {
      name: 'limit',
      type: GraphQLInt,
    },
    offset: {
      name: 'offset',
      type: GraphQLInt,
    }
  },
  resolve: (user, args) =>  (
    Note.findAll({ where: {
        id: args.id,
      },
      limit: args.limit,
      offset: args.offset,
    })
  )
};
```

Does this solve your problem? If not please describe your problem with more details.

**Comment by holidaycottages** [comment]
Thank you

That is what I was thinking of how to do it, just now when I implement that and do not send in the id the SELECT statement puts in : 

`WHERE id = NULL`

And then returns no results, how to not add that to the WHERE clause if it doesnt exist?

**Comment by aichbauer** [comment]
okay...

we can check if a argument was set...

this is just one way to do this, there are maybe better solutions for this.
```js
resolve: (user, args) =>  {
  if(args.id) {
    return Note.findAll({ where: {
        id: args.id,
      },
      limit: args.limit,
      offset: args.offset,
    });
  }

  return Note.findAll({
      limit: args.limit,
      offset: args.offset,
    });
}
```

**Comment by holidaycottages** [comment]
Yea I might need to find a better way, as if I have say 10 parameters I don't want to put a conditional around each one of those as that would be hard to manage...

**Comment by aichbauer** [comment]
Yeah, a better solution would be to create different query's, one with id and one without. Also often you do not need all args in query's. You have to know which args are useful and which are not. only keep those args which you are using in your application to query.

**Comment by holidaycottages** [comment]
Ah so taking your example above you would add another query to the file but with a different arg in it?

```const noteIdQuery = {
  type: new GraphQLList(NoteType),
  args: {
    id: {
      name: 'id',
      type: GraphQLInt,
    },
    limit: {
      name: 'limit',
      type: GraphQLInt,
    },
    offset: {
      name: 'offset',
      type: GraphQLInt,
    }
  },
  resolve: (user, args) =>  (
    Note.findAll({ where: {
        id: args.id,
      },
      limit: args.limit,
      offset: args.offset,
    })
  )
};

const noteTitleQuery = {
  type: new GraphQLList(NoteType),
  args: {
    name: {
      title: 'title',
      type: GraphQLString,
    },
    limit: {
      name: 'limit',
      type: GraphQLInt,
    },
    offset: {
      name: 'offset',
      type: GraphQLInt,
    }
  },
  resolve: (user, args) =>  (
    Note.findAll({ where: {
        title: args.title,
      },
      limit: args.limit,
      offset: args.offset,
    })
  )
};```

And so on?

**Comment by aichbauer** [comment]
For example.

But you have to find a way that works for you the best. There are hundreds of possible solutions to this problem...

**Comment by holidaycottages** [comment]
I appreciate the help but I am struggling to find a way that enables me to conditionally add the args in, without creating a lot of combinations etc.

The idea is I am building a search and so can have a lot of args and any one of them can be true or have a value.

It only doesnt work when you explicitly put in args.id etc, when it was just args then it seemed to work out for itself if there was a value or not.

But having it like that would mean that limit and offset would go in the WHERE clause and that wouldnt work.

If you can point me in any good direction I would appreciate the help

**Comment by aichbauer** [comment]
You could do something like:
```js
args: {
    id: {
      name: 'id',
      type: GraphQLInt,
    },
    name: {
      name: 'name',
      type: GraphQLInt,
    },
    limit: {
      name: 'limit',
      type: GraphQLInt,
    },
    offset: {
      name: 'offset',
      type: GraphQLInt,
    }
  },
  resolve: (note, args) => {
    let thisArgs = {};
    Object.entries(args).forEach((entry) => {
      if(entry[1] && entry[0] !== 'limit' && entry[0] !== 'offset'){
        thisArgs = {
          ...thisArgs,
          [entry[0]]: entry[1],
        };
      }
    });

    return Note.findAll({ 
      where: thisArgs,
      limit: args.limit,
      offset: args.offset,
    });
  }
```

This would check if a arg is passed and only if it is passed it gets to the object `thisArgs` and with `thisArgs` you call the Note.findAll()...
