### ISSUE TITLE
Get /graphql interface working

### ISSUE THREAD

**Issue by holidaycottages** [aichbauer/express-graphql-boilerplate#16]
I have tried to implement the code example you give to get the GraphQL web interface working but I get an error:

`ReferenceError: GraphHTTP is not defined`

I am assuming I need to require something else to get this to work?

Below is a slightly modified version of the example:

`api.get('/graphql', GraphHTTP({
  schema,
  pretty: true,
  graphiql: true,
}));
api.post('/graphql', GraphHTTP({
  schema,
  pretty: true,
  graphiql: true,
}));`

**Comment by aichbauer** [comment]
If your using [express graphql](https://github.com/graphql/express-graphql) you need to `const GraphHTTP = require('express-graphql');` but since this project switched to `apollo server` I would recommend to use `const { graphiqlExpress } = require('apollo-server-express');` and then use it like

```js
// bodyParser is needed just for POST.
app.use('/graphql', bodyParser.json(), graphqlExpress({ schema: myGraphQLSchema }));
app.get('/graphiql', graphiqlExpress({ endpointURL: '/graphql' })); // if you want GraphiQL enabled
```

take a look at the `api.js` there you can add it.

**Comment by holidaycottages** [comment]
Works fantastic!

Now how does one send the JWT to it so it can be used?

**Comment by aichbauer** [comment]
Thats the tricky thing, GraphiQL does not support that out of the box. but if you install a package like `express-graphiql-toolbox` you could have the same with header support.

```js
const graphiqlExpress = require('express-graphiql-toolbox');

app.use('/graphql', bodyParser.json(), graphqlExpress({ schema: myGraphQLSchema }));
app.get('/graphiql', graphiqlExpress({ endpoint: '/graphql' })); // if you want GraphiQL enabled
```

but here you have to set the empty variables your self. on the bottom click on query variables and put `{}` in it if you query.

**Comment by aichbauer** [comment]
@holidaycottages does it work for you?

**Comment by holidaycottages** [comment]
@aichbauer I installed it and the new interface loads, but every time I execute a query I get an error:

"Variables are invalid JSON."

And there is a console error, so I feel like I am 99% there, but it just wont work

**Comment by holidaycottages** [comment]
I used graphql-playground-middleware-express instead and works great

**Comment by aichbauer** [comment]
Great... yeah thats what I thought... you have to add the variables yourself, which is made with `{}` at the bottom... but if `graphql-playground-middleware-express` works great, I will test it out and add a pull request to add this package instead.
