### ISSUE TITLE
Missing function?

### ISSUE THREAD

**Issue by holidaycottages** [aichbauer/express-graphql-boilerplate#17]
`notes: {
      type: new GraphQLList(NoteType),
      resolve: (user) => user.getNotes(),
    },`

I cant find user.getNotes() function?

**Comment by aichbauer** [comment]
This function is a internal of Sequelize.

Take a look at [the User model](https://github.com/aichbauer/express-graphql-boilerplate/blob/17ddd02ceba02b253ed62bb12a263b4feea1e6b6/api/models/User/User.js#L37) and [the Sequelize documentation](http://docs.sequelizejs.com/manual/tutorial/associations.html#n-m).

When you add a one to many association you can get all associatied entries from the model.

**Comment by holidaycottages** [comment]
Got you!

Works perfectly

How can you query that data?

For example how could you get all the users that have a certain note? Or would that just be another query written the other way around?

**Comment by aichbauer** [comment]
as the note is part of the user type:

all users with notes
```sh
{
  user {
    username
    notes {
      id
      note
    }
  }
}
```

specific user 
```sh
{
  user(id: "1") {
    username
    notes {
      id
      note
    }
  }
}
```

**Comment by holidaycottages** [comment]
But what about all users that gave a specific note? Say 10 users out of 100 had the same note and I want the users from that?

**Comment by aichbauer** [comment]
The current implementation does not allow that because every note is owned by one specific user... but if you want to get every user how has ever written the same note, you could solve this with input types.
