### ISSUE TITLE
How to perform a raw query?

### ISSUE THREAD

**Issue by holidaycottages** [aichbauer/express-graphql-boilerplate#21]
So write my own SQL and not use sequelize?

Just because I have a very complex query that I am not sure sequelize can handle or would take me too long to work out how to get the same result.

**Comment by aichbauer** [comment]
You can perfrom raw queries in sequelize using `sequelize.query('SELECT  * FROM whateverTableYouNeed');`

for more information please look into the documentation of [sequelize on how to use raw queries](http://docs.sequelizejs.com/manual/tutorial/raw-queries.html#raw-queries)

**Comment by holidaycottages** [comment]
Can I access and use the database var thats been setup already in the project or do I need to create another instance?

**Comment by aichbauer** [comment]
`const sequelize = require('../../../config/database');`

import the database and the use it like

`sequelize.query('SELECT * FROM myTable');`

**Comment by holidaycottages** [comment]
Brilliant.

I assume if I use my own raw query I will need to construct the result to match the type? 

Ignore the above, just tried it and worked!

**Comment by aichbauer** [comment]
Exactly. Cause if you use aliases in your raw query that do not match the definitions in the type GraphQL would not be able to resolve the fields.

**Comment by holidaycottages** [comment]
One more thing on this, I want to construct the SELECT statement so that it only selects out the columns requested by the graphql query, I cant work out how I can find these?

So if someone had the following pseudo query:

`query{
    user{
       name
       email
     }
}`

And I was writing my own SELECT, how can I get the `name and email` request vars to then build a select statement that only includes those fields?

Ive searched on the internet and found you need to do something with `info.fieldNodes` but I cant seem to see the request object in there
