### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by workteam123** [aichbauer/express-graphql-boilerplate#24]
Hi Guys - great work and thank you - I get this deprecation warning when running - sequelize deprecated String based operators are now deprecated.  Is it a simple fix?
Thanks again

**Comment by aichbauer** [comment]
Hey, thanks for your issue.

I will take a look into this deprecation warning. But at first sight I guess it could be fixed by explicitly telling Sequelize which operators you want to use (see [secure operators](http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-security))

**Comment by aichbauer** [comment]
Hey @workteam123,

I already worked out a fix for it, I will update the master branch as soon I have time. So I think tomorrow it will be fixed.

**Comment by aichbauer** [comment]
closed by #25

**Comment by aichbauer** [comment]
closed by #25
