### ISSUE TITLE
access to /graphql via /explore

### ISSUE THREAD

**Issue by joggerjoel** [aichbauer/express-graphql-boilerplate#28]
<img width="782" alt="screen shot 2018-08-19 at 10 44 01 am" src="https://user-images.githubusercontent.com/6584275/44313263-51c39800-a3d3-11e8-9f97-b5674cf9ab8a.png">
`location / {
    proxy_pass       http://localhost:2017;
    proxy_set_header Host      $host;
    proxy_set_header X-Real-IP $remote_addr; 
}`

need documentation to setup nginx config

**Comment by devomacdee** [comment]
Any update on this?

**Comment by aichbauer** [comment]
@joggerjoel @devomacdee I will work out an example of how to deploy this project to production with `nginx` in the next week.
