### ISSUE TITLE
Help Wanted : In Update User Mutaion

### ISSUE THREAD

**Issue by krunvaghela** [aichbauer/express-graphql-boilerplate#40]
# i Wanted Map Or Graph of Update User Mutation ..

**Comment by krunvaghela** [comment]
Update Not Working .. @aichbauer Please Help Me

**Comment by aichbauer** [comment]
I will need a little bit more information of what you are trying to do.

Can you show me the code you are using?
Node.js version?
Operating System?

**Comment by krunvaghela** [comment]
@aichbauer What Will be Graphql Mutaion for Update User .. i want String Like Which You Provided for Notes
