### ISSUE TITLE
cross-env NODE_ENV=development && node ./api/api.js -- npm ERR! code ELIFECYCLE npm ERR! errno 1

### ISSUE THREAD

**Issue by sankar2389** [aichbauer/express-graphql-boilerplate#8]
F:\nodejs\Gold\express-graphql-boilerplate-master>npm start

> express-rest-api-boilerplate@0.0.0 prestart F:\nodejs\Gold\express-graphql-boilerplate-master
> npm run create-sqlite-db

> express-rest-api-boilerplate@0.0.0 create-sqlite-db F:\nodejs\Gold\express-graphql-boilerplate-master
> shx touch ./db/database.sqlite

> express-rest-api-boilerplate@0.0.0 start F:\nodejs\Gold\express-graphql-boilerplate-master
> npm run nodemon

> express-rest-api-boilerplate@0.0.0 nodemon F:\nodejs\Gold\express-graphql-boilerplate-master
> nodemon --exec npm run dev

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run dev`

> express-rest-api-boilerplate@0.0.0 dev F:\nodejs\Gold\express-graphql-boilerplate-master
> cross-env NODE_ENV=development && node ./api/api.js

only development, staging, test and production are valid NODE_ENV variables but undefined is specified
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-rest-api-boilerplate@0.0.0 dev: `cross-env NODE_ENV=development && node ./api/api.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-rest-api-boilerplate@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sankar\AppData\Roaming\npm-cache\_logs\2017-12-25T03_40_52_904Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...

**Comment by aichbauer** [comment]
Did you run `npm install` or `yarn` before `npm start`?

**Comment by sankar2389** [comment]
Yes

**Comment by sankar2389** [comment]
@aichbauer How to resolve this issue?

**Comment by aichbauer** [comment]
@sankar2389 it is possible that cross-env is not working... if you only run it on windows you could try to change `cross-env NODE_ENV=development && node ./api/api.js` to `set NODE_ENV=development && node ./api/api.js`

**Comment by sankar2389** [comment]
@aichbauer > set NODE_ENV=development && node ./api/api.js

only development, staging, test and production are valid NODE_ENV variables but development  is specified
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-rest-api-boilerplate@0.0.0 dev: `set NODE_ENV=development && node ./api/api.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-rest-api-boilerplate@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sankar\AppData\Roaming\npm-cache\_logs\2018-01-03T05_00_37_856Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...

**Comment by sankar2389** [comment]
@aichbauer > set NODE_ENV=development && node ./api/api.js

only development, staging, test and production are valid NODE_ENV variables but development  is specified
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-rest-api-boilerplate@0.0.0 dev: `set NODE_ENV=development && node ./api/api.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-rest-api-boilerplate@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sankar\AppData\Roaming\npm-cache\_logs\2018-01-03T05_00_37_856Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...

**Comment by aichbauer** [comment]
So we changed `only development, staging, test and production are valid NODE_ENV variables but undefined is specified` to `only development, staging, test and production are valid NODE_ENV variables but development is specified` the problem is with the database I guess... what db you are using? What did you specified in the `config/connection.js`?

**Comment by sankar2389** [comment]
First I created a DB named 'graphql' in MySQL.

Then I updated connection.js as follows 

Const development = {
database: 'graphql',
username: 'roor',
password: '',
host: 'localhost',
dialect: 'sqlite' || 'mysql' || 'postgres',
};

**Comment by sankar2389** [comment]
First I created a DB named 'graphql' in MySQL.

Then I updated connection.js as follows 

const development = {
database: 'graphql',
username: 'root',
password: '',
host: 'localhost',
dialect: 'sqlite' || 'mysql' || 'postgres',
};

**Comment by aichbauer** [comment]
Set dialect to 'mysql'. Is mysql running?

**Comment by rayehizoba** [comment]
Hi Aichbauer. I'm experiencing this issue also. Please how do I resolve it?

**Comment by sankar2389** [comment]
I couldn't able to solve this. So I started following some other tutorial to start with. I think instead of trying things with someone's boilerplate, we can try from scratch is better.

**Comment by aichbauer** [comment]
@rayehizoba I figured out that cross-env is only working when you do not use && between comands... so in your package.json you can change `"dev": "cross-env NODE_ENV=develompent && node ./api/api.js",` to `"dev": "cross-env NODE_ENV=develompent node ./api/api.js",`which should do the trick...

**Comment by rayehizoba** [comment]
Thanks @aichbauer for your timely response and a very clean, usable boilerplate. I do hope to contribute to this boilerplate, as I would be using it quite often. I intend to add social authentication. Thanks again.

**Comment by aichbauer** [comment]
@sankar2389 would be great if you help to improve the the boilerplate. If you have some ideas just open an issue and we can discuss this, and also there are some open issues, maybe you want to start there?

**Comment by sankar2389** [comment]
@aichbauer sure I'll help whatever I could.
